spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-7OAMV2O;databaseName=sms
    username: sa
    password: Home123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  data:    mongodb:      uri: mongodb://user:1234@firstcluster-shard-00-00.heifp.mongodb.net:27017,firstcluster-shard-00-01.heifp.mongodb.net:27017,firstcluster-shard-00-02.heifp.mongodb.net:27017/<testDB>?ssl=true&replicaSet=atlas-4ckxpg-shard-0&authSource=admin&retryWrites=true&w=majority