spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://DESKTOP-7OAMV2O;databaseName=sms
    username: sa
    password: Home123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update  data:    mongodb:
      database: testDB
      host: localhost
      port: 27017
server:  port: 8102